#Week 3 R Programming Assignment

#Designs functions to create a matrix that can cache its inverse

#This function creates a list used to pass functions to the cacheSolve function
#Components: set, get, setInverse, getInverse
#Creates variable m which will store cached data
makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setInverse <- function(solve) m <<- solve
  getInverse <- function() m
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}

#This function takes the list generated by makeCacheMatrix as its input
#If cached data is already present (by running getInverse function, this data is displayed instead of repeating the calculation
#Otherwise, calls the get, solve, and setInverse functions
cacheSolve <- function(x, ...) {
  m <- x$getInverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setInverse(m)
  m
}
